import type { Metadata } from "next";
import "@/app/styles/globals.css";
import Header from "../Layout/Header";
import Footer from "../Layout/Footer";

export const metadata: Metadata = {
  title: "فرانتیون | Frontioun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
