import BaseButton from "@/components/BaseButton";
import Head from "next/head";
import classes from "../styles/pages/index";

export default function Home() {
  return (
    <main className={classes.main.wrapper}>
      <Head>
        <title> فرانتیون | Frontioun</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/favicon.ico" />
      </Head>

      <section className={classes.main.hero.wrapper}>
        <div className={classes.main.hero.text.wrapper}>
          <h1 className={classes.main.hero.text.title}>
            فرانت شروع برنامه‌نویسی ست!
          </h1>

          <p className={classes.main.hero.text.subTitle}>
            عمیق یاد می‌گیری چون عمیق بودن رسالت ماست
          </p>

          <BaseButton />
        </div>

        <img
          className="w-[19rem] h-[27rem] relative"
          src="/image/banner2.png"
          alt="banner_image"
        />
        <div className="absolute z-20 w-full h-32 hero-shadow-gradient dark:hero-shadow-gradient-dark -bottom-0" />
      </section>
    </main>
  );
}
