import Head from "next/head";
import Image from "next/image";
import BaseButton from "@/components/BaseButton";
import WaveArrow from "../components/svgs/WaveArrow";
import CourseCard from "@/components/CourseCard";
import GarrantyCard from "@/components/GarrantyCard";
import { SlDiamond } from "react-icons/sl";
import { SiReactos } from "react-icons/si";
import { HiOutlineWrenchScrewdriver } from "react-icons/hi2";
import { GiMoneyStack } from "react-icons/gi";
import { IoIosArrowBack } from "react-icons/io";
import { BiSupport } from "react-icons/bi";

export default function Home() {
  const ReactImage = {
    src: "/images/react.jpg",
    alt: "react image",
    width: 290,
    height: 100,
  };

  const HtmlImage = {
    src: "/images/html.jpg",
    alt: "Htmlimage",
    width: 290,
    height: 100,
  };

  const CssImage = {
    src: "/images/css.avif",
    alt: "Css image",
    width: 290,
    height: 100,
  };

  const JSImage = {
    src: "/images/javascript.jpg",
    alt: "Js image",
    width: 500,
    height: 200,
  };
  return (
    <main className="container pt-32 lg:pt-0">
      <Head>
        <title> فرانتیون | Frontioun</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/favicon.ico" />
        <link rel="preload" href="/images/banner.png" as="image" />
      </Head>

      <section className="relative flex flex-col-reverse py-8 m-auto xl:flex-row xl:w-10/12">
        <div className="text-center xl:text-right">
          <h1 className="hero_text text-[50px] leading-[1.5] md:leading-[1.3] xl:text-[65px] text-primary-dark dark:text-primary-light">
            فرانت شروع برنامه‌نویسی ست!
          </h1>

          <p className="py-3 border-b-2 md:w-10/12 md:text-lg md:m-auto border-zinc-200 dark:border-primary-dark text-primary-dark dark:text-primary-light">
            عمیق یاد می‌گیری چون عمیق بودن رسالت ماست
          </p>

          <BaseButton
            name="بریم تو کارش!"
            classes="mt-6 py-4 text-lg text-white bg-blue-700 rounded-full w-1/2 mx-auto xl:mx-0 xl:w-5/12 hover:bg-blue-600"
          />
        </div>

        <div className="relative xl:w-7/12">
          <Image
            className="w-48 m-auto lg:w-[315px]"
            src="/images/banner.png"
            alt="banner_image"
            width={290}
            height={100}
            priority
          />
          <div
            id="banner-shadow"
            className="absolute z-10 w-screen h-32 hero-shadow-gradient dark:hero-shadow-gradient-dark -bottom-[9px] blur-sm rounded-[19px] left-0 md:right-0 md:translate-x-0"
          />
        </div>
      </section>

      <WaveArrow />

      <section className="px-4 pb-16 pt-7">
        <ul className="flex flex-col items-center justify-center gap-16 font-bold lg:flex-row text-md whitespace-nowrap text-slate-800">
          <GarrantyCard title="دوره‌های متنوع">
            <SiReactos className="mb-4 text-blue-500" size={35} />
          </GarrantyCard>

          <GarrantyCard title="تضمین کیفیت">
            <SlDiamond className="mb-4 text-blue-500" size={35} />
          </GarrantyCard>

          <GarrantyCard title="کاربردی و موثر">
            <HiOutlineWrenchScrewdriver
              className="mb-4 text-blue-500"
              size={35}
            />
          </GarrantyCard>

          <GarrantyCard title="تضمین بازگشت وجه">
            <GiMoneyStack className="mb-4 text-blue-500" size={45} />
          </GarrantyCard>

          <GarrantyCard title="همراه با پشتیبانی">
            <BiSupport className="mb-4 text-blue-500" size={40} />
          </GarrantyCard>
        </ul>
      </section>

      <section>
        <div className="flex items-center justify-between pb-16">
          <h2 className="text-xl font-black md:text-3xl text-slate-800 dark:text-slate-100">
            جدیدترین دوره‌ها
          </h2>
          <div className="text-sm font-semibold cursor-pointer center-center gap-x-2 text-zinc-500 hover:text-zinc-800 dark:text-slate-100 dark:hover:text-slate-300">
            <span>مشاهده همه دوره‌ها</span>
            <IoIosArrowBack size={20} />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-x-6 gap-y-20">
          <CourseCard image={JSImage} title="دوره جاوااسکریپت" price={1000000}>
            <p className="line-clamp-3">
              توی این دوره شما راه و روش برنامه نویسی جاوااسکریپت رو یاد میگیرید
              و آماده میشید که از کتابخونه‌ها و فریمورک‌های اون استفاده کنید
            </p>
          </CourseCard>

          <CourseCard image={ReactImage} title="دوره ریکت" price={1500000}>
            <p className="line-clamp-3">
              توی این دوره شما یاد میگیرید که با استفاده از امکانات بی‌نظیر ریکت
              یک وبسایت رو بصورت کامل طراحی کنید
            </p>
          </CourseCard>

          <CourseCard image={HtmlImage} title="دوره اچ تی ام ال" price={300000}>
            <p className="line-clamp-3">
              توی این دوره شما یاد میگیرید که با استفاده از اچ تی ام ال استخوان
              بندی یک وبسایت رو بصورت کامل طراحی کنید بندی یک وبسایت رو بصورت
              کامل طراحی کنید بندی یک وبسایت رو بصورت کامل طراحی کنید
            </p>
          </CourseCard>
          <CourseCard image={CssImage} title="دوره سی اس اس" price={500000}>
            <p className="line-clamp-3">
              توی این دوره شما یاد میگیرید که با استفاده از اچ تی ام ال استخوان
              بندی یک وبسایت رو بصورت کامل طراحی کنید بندی یک وبسایت رو بصورت
              کامل طراحی کنید بندی یک وبسایت رو بصورت کامل طراحی کنید
            </p>
          </CourseCard>
        </div>
      </section>
    </main>
  );
}
